const PendingAppointmentsData = [
  {
    serviceName: ["Hair Cut", "Spa", "Nails"],
    clientName: "Amanda",
    contact: 234567891,
    dateTime: "12.09.2024 - 12.53 PM",
    workerName: "Linda",
    duration: "1h 15min",
    AssignEmployee: "Assign",
    Cancel: "Cancel",
  },
  {
    serviceName: ["Hair Cut", "Spa", "Nails"],
    clientName: "Arjun",
    contact: 234567891,
    dateTime: "03.05.2024 - 10.53 PM",
    workerName: "Moore",
    duration: "45min",
    AssignEmployee: "Assign",
    Cancel: "Cancel",
  },
  {
    serviceName: ["Hair Cut", "Spa", "Nails"],
    clientName: "kresha",
    contact: 234567891,
    dateTime: "25.05.2025 - 02.53 PM",
    workerName: "Nellie",
    duration: "15min",
    AssignEmployee: "Assign",
    Cancel: "Cancel",
  },
  {
    serviceName: ["Nails"],
    clientName: "kresha",
    contact: 234567891,
    dateTime: "25.05.2025 - 02.53 PM",
    workerName: "Nellie",
    duration: "15min",
    AssignEmployee: "Assign",
    Cancel: "Cancel",
  },
  {
    serviceName: ["Nails"],
    clientName: "kresha",
    contact: 234567891,
    dateTime: "25.05.2025 - 02.53 PM",
    workerName: "Nellie",
    duration: "15min",
    AssignEmployee: "Assign",
    Cancel: "Cancel",
  },
  {
    serviceName: ["Hair Cut", "Spa"],
    clientName: "kresha",
    contact: 234567891,
    dateTime: "25.05.2025 - 02.53 PM",
    workerName: "Nellie",
    duration: "15min",
    AssignEmployee: "Assign",
    Cancel: "Cancel",
  },
  {
    serviceName: ["Nails"],
    clientName: "kresha",
    contact: 234567891,
    dateTime: "25.05.2025 - 02.53 PM",
    workerName: "Nellie",
    duration: "15min",
    AssignEmployee: "Assign",
    Cancel: "Cancel",
  },
  {
    serviceName: ["Hair Cut", "Spa", "Nails"],
    clientName: "kresha",
    contact: 234567891,
    dateTime: "25.05.2025 - 02.53 PM",
    workerName: "Nellie",
    duration: "15min",
    AssignEmployee: "Assign",
    Cancel: "Cancel",
  },
];

export default PendingAppointmentsData;
